"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FlightGearPlaneDownloader_Github.py']
APP_NAME = "FlightGearAircraftAndLivery_Github"
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    #'iconfile': 'Flight_Gear.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Flight Gear Aircraft And Livery Downloader",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright  2016,  Carter Rhea, All Rights Reserved"
}
}

setup(
      app=APP,
      data_files=DATA_FILES,
      options={'py2app': OPTIONS},
      setup_requires=['py2app'],
      )
